version: "3.9"

services:
  database:
    image: postgres
    container_name: stockpro_database_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stockpro
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
  redis:
    driver: local